accept = [200, 206, 308, 429]

max_retries = 2
retry_wait_time = 5
timeout = 20

max_concurrency = 8

cache = true
max_cache_age = "1d"

include_mail = false
include_fragments = false
method = "get"

user_agent = "inngest-link-check/1.0 (https://www.inngest.com)"

exclude_path = [
  "node_modules",
  ".next",
  "out",
  "public",
  "snippets",
]
