#!/bin/bash

curl -X GET \
  'https://public-api.drata.com/public/vendors?limit=50' \
  -H "Authorization: Bearer $DRATA_API_KEY" | jq '[.data[] | select(.hasPii == true) | select(.status == "ACTIVE") | {name,status,dataStored,notes}]' > data/vendors.json
