"use client";

import StippleCanvas, {
  type StippleCanvasProps,
} from "@/components/v1/StippleCanvas";

/**
 * Sandboxes hero stipple. Manifest is generated by
 * `pnpm v1:extract-sandboxes-dots`: a nested square (thick frame,
 * inner square, and the gap between them) filling the visible band
 * of a 1000×1600 frame. Entrance is the shared StippleCanvas pour;
 * the field then holds still.
 */
type Props = Pick<StippleCanvasProps, "className" | "style" | "onReady">;

export default function SandboxesDotsCanvas(props: Props) {
  return (
    <StippleCanvas
      {...props}
      manifestInlineId="sandboxes-dots-data"
      manifestSrc="/assets/v1/sandboxes-hero/dots.json"
      fit="cover"
      ambientAmpPx={0}
      craterStrengthPx={0}
      // 1000-wide manifest on a ~475px panel is ~0.5×. The default 0.6
      // CSS radius lands sub-pixel, so bump it the same way Agent Evals
      // does: 2.1 × ~0.5 ≈ 1px dots.
      particleRadiusCss={2.1}
    />
  );
}
