name: On Cloudflare Deploy

on: push

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: '63116bbc42092d732b07f97961ce5121'
          project: 'website'
          commitHash: ${{ github.sha }}
      - if: steps.deployment.outputs.success == 'true'
        run: |
          npx broken-link-checker ${{ steps.deployment.outputs.url }} \
            --recursive --host-requests 10 --requests 10 --follow \
            --exclude '${{ steps.deployment.outputs.url }}/test/' \
            --exclude 'https://www.iubenda.com' \
            --exclude ' https://docs.github.com'
