name: On Deployment

on: push

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 480

      - name: Display deployment URL
        run: "echo Preview URL: ${{steps.deployment.outputs.url}}"

      - uses: actions/checkout@v2.1.0

        # Just install only the deps we need
      - name: Install dependencies
        if: steps.deployment.outputs.url != ''
        run: yarn add broken-link-checker @types/node

      - name: Run broken-link-checker
        if: steps.deployment.outputs.url != ''
        run: yarn broken-link-checker ${{steps.deployment.outputs.url}}
